export default {
  SET_QUESTION_TEXT: 'question/SET_QUESTION_TEXT',
  CREATE_QUESTION_OPTION: 'question/CREATE_QUESTION_OPTION',
  SET_QUESTION_OPTION: 'question/SET_QUESTION_OPTION',
  REMOVE_QUESTION_OPTION: 'question/REMOVE_QUESTION_OPTION',
};
